<div class="links">
	<div class="block-title">
		<strong><span>My Account</span></strong>
        <div class="underline"></div>
	</div>
	<ul>
		<li><a href="{{store url=""}}about-magento-demo-store/">Sign In</a></li>
		<li><a href="{{store url=""}}contacts/">View Cart</a></li>
		<li><a href="{{store url=""}}customer-service/">My Wishlist</a></li>
        <li><a href="{{store url=""}}customer-service/">Check Out</a></li>
        <li><a href="{{store url=""}}customer-service/">Track My Order</a></li>
	</ul>
</div>